language: node_js
script: npm run cover
node_js:
  - '4.1'
  - '4.0'
  - '0.12'
  - '0.11'
  - '0.10'
  - stable
after_success:
  - npm run coveralls
deploy:
  provider: npm
  email: freeformsystems@gmail.com
  api_key:
    secure: LGU1MMW9jq9kBIHeEsPU9X0Ubw1JXHfYOV97M01ObE9fHJNwZ112qXVR9EU+fKU08fuF2mM2e6z00PCmfCiXbZu4tr2yKRdDJSGTBo6Zv8lWbMpCjymQPJhlpJITjlTssPxXQcq7Sn/3tLtKD9I2WJR+L02FBpUcLVYKw/Jh/vfvFjps+6tqMEmwxMdAR4Oze6xocG/SPed0bSOzknbr7QGURby4yw9HTwQS+iAQ97N720vDGkZHU1YKJkfJ6VUaA9pJtcGYyV3hxyxvxTegIeviTMIGwiemok51ziEMDOIrPWlkamJn18I7JS+zE2Zw0Fd8LzxP6rS27B4SfaW4WKa3dBQ32nwWygzbiUf7TQxQ8569b6koW85OCT3vnbqBbglk6EfCyMgQ+UMj/asIwNelOEW+63lvfM/6dzZK9Z8SiEKXNEDkPKEqbeugJEsEnZrFYPpsFcfAS4Se4JmonnR6GGeU6r7ERSPxECD5ZiwToC5fVWuNaG4dn3pHU0XAySJ+mn7wUgT0xfE0oOaM7shWEd18oN+yRthzUq8y+1J7gcLSOKG+YEIrDhmQz81JRassNAxYMl/WH8xVzpsMQ63A3EREeSiVL5IQ2GNw35beain+EHjZrFZ9aEBTXeXbKByQQK/YBNbn/TcjblazWtY67mSmnGG4uttyXRMAPdk=
  on:
    tags: true
    repo: tmpfs/stream-lines
    node: '4.1'
